### ISSUE TITLE
Add command line executable

### ISSUE THREAD

**Issue by Ben-Mack** [romigrou/ssim#1]
Thank you for open source this powerful lib!

It would be great if there's a command line executable available so people like me (who have not much C experience) can easily try and integrate the tool into our pipeline.

**Comment by tados000** [comment]
+1

**Comment by romigrou** [comment]
I'm on it and it's almost done, but can't give you an ETA, it's low prio to me.

**Comment by romigrou** [comment]
Just pushed a commit that adds a command line utility and a sample code.
