### ISSUE TITLE
Exemple

### ISSUE THREAD

**Issue by tados000** [romigrou/ssim#2]
Bonjour,

Serait-il possible d'ajouter un exemple d'utilisation (comparaison de 2 JPEG) en C car je tourne un peu en rond pour l'utilisation
Merci

**Comment by romigrou** [comment]
Les tests unitaires devraient pouvoir vous aider. Je suis également en train de rajouter un (petit) outil en ligne de commande qui pourra servir d'exemple. En revanche, je ne pense pas que j'ajouterai de fichier d'exemple dédié.

**Comment by tados000** [comment]
Merci pour ces précisions et félicitation pour ce beau projet !

________________________________
De : Romain Bailly <notifications@github.com>
Envoyé : mercredi 3 février 2021 15:04
À : romigrou/ssim <ssim@noreply.github.com>
Cc : tados000 <tados000@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [romigrou/ssim] Exemple (#2)


Les tests unitaires devraient pouvoir vous aider. Je suis également en train de rajouter un (petit) outil en ligne de commande qui pourra servir d'exemple. En revanche, je ne pense pas que j'ajouterai de fichier d'exemple dédié.

**Comment by romigrou** [comment]
Finalement, j'ai ajouté un code d'exemple qui couvre l'usage le plus basique.
